name = "vaccination-worker"
type = "webpack"

account_id = "<YourAccountID>"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [ 
         { binding = "vaccination_KV", id = "<HAS TO BE CREATED>" }
]
