name = "vaccination-worker"
type = "webpack"

account_id = "<YourAccountID>"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [ 
         { binding = "vaccination_KV", id = "e2e2e6b9ad824bc986feeba870f4ec6e" }
]
